project:
  type: website
  output-dir: docs

website:
  title: ""
  google-analytics: "G-5N965RRHS4"
  favicon: images/favicon.ico
  navbar:
    logo: images/COReS-Logo-negative.png
    logo-alt: COReS Project Logo
    logo-href: https://cores-hub.io
    background: dark
    right:
      - href: index.qmd
        text: Home
      - text: "Community"
        menu: 
        - join.qmd
        - text: "Become a Community Member"
          file: about-cores/become-member.qmd
        - href: https://cores.zulipchat.com/
          text: To the Discussion Forum
          icon: bi-box-arrow-up-right
        - text: "Using the Discussion Forum"
          file: about-cores/using-zulip.qmd
        - text: "Our Partners"
          file: about-cores/partners.qmd
        - text: "Become a Partner"
          file: about-cores/become-partner.qmd
        - about-cores/policies.qmd
        - about-cores/code-of-conduct.qmd  
      - text: "Systematic Reviews"
        menu: 
        - learn.qmd
        - perform.qmd
      - text: "Synthesis-Ready Research"
        menu: 
          - synthesis-ready.qmd
          - text: Design
            href: synthesis/design.qmd
          - text: Register
            href: synthesis/preregister.qmd
          - text: Disseminate
            href: synthesis/disseminate.qmd
      - events.qmd
      - contact.qmd

    tools:
      - href: https://linkedin.com/company/communities-for-open-research-synthesis 
        icon: linkedin
        target: _blank
      - href: https://camarades.us17.list-manage.com/subscribe?u=f0edb12e4958380a0247fc589&id=8befbe2fcc
        icon: newspaper
        target: _blank
    pinned: true
  sidebar: 
    - title: "Community"
      style: "docked"
      contents:
      - section: "COReS Community"
        contents:      
        - join.qmd
        - text: "Become a Community Member"
          file: about-cores/become-member.qmd
      - text: "---"
      - section: "Discussion Forum"
        contents:  
        - href: https://cores.zulipchat.com/
          text: To the Discussion Forum
          icon: bi-box-arrow-up-right
        - text: "Using the Discussion Forum"
          file: about-cores/using-zulip.qmd
      - text: "---"
      - section: "Partners"
        contents:  
        - text: "Our Partners"
          file: about-cores/partners.qmd
        - text: "Become a Partner"
          file: about-cores/become-partner.qmd
      - text: "---"
      - section: "Policies"
        contents:  
        - about-cores/policies.qmd
        - about-cores/code-of-conduct.qmd


    - title: "SR"
      style: "docked"
      contents:
        - learn.qmd       
        - perform.qmd     
        
    - title: "Synthesis-Ready"
      style: "docked"
      contents:
        - synthesis-ready.qmd
        - text: "Design Experiments"
          file: synthesis/design.qmd
        - text: "Register Experiments"
          file: synthesis/preregister.qmd
        - text: "Disseminate Primary Research"
          file: synthesis/disseminate.qmd


  page-footer:
    left: "Project funded by [Volkswagen Stiftung](https://www.volkswagenstiftung.de/en/news/interview/quality-preclinical-research-networked-rather-alone)."
    center: "We are a community. You can read about our [Policies](/about-cores/policies.qmd) and [Code of Conduct](/about-cores/code-of-conduct/), which applies across our community platform, digital and in person events." 
    right: 
      - icon: linkedin 
        href: https://linkedin.com/company/communities-for-open-research-synthesis 
      - href: https://camarades.us17.list-manage.com/subscribe?u=f0edb12e4958380a0247fc589&id=8befbe2fcc
        icon: newspaper
        target: _blank
      - icon: envelope-at-fill
        href: mailto:camarades.berlin@charite.de
        target: _blank
  reader-mode: false
  search: true


format:
  html:
    theme:
      - cosmo
      - brand
      - style.scss
    toc: true
    page-layout: full




