project:
  type: website

website:
  title: ""
  favicon: images/favicon.ico
  navbar:
    logo: images/cores-Logo-Subline.png 
    logo-alt: COReS Project Logo
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - learn.qmd
      - perform.qmd
      - synthesis-ready.qmd
      - contact.qmd
      - href: https://cores.zulipchat.com/
        text: To the Discussion Forum
        icon: bi-box-arrow-up-right
    tools:
      - href: https://github.com
        icon: github
  page-footer:
    left: "Project funded by [Volkswagen Stiftung](https://www.volkswagenstiftung.de/en/news/interview/quality-preclinical-research-networked-rather-alone)."
    center: "We are a community. You can read about our [Equity, Diversity & Inclusion Policy](/equity-diversity-and-inclusion/).
Read more about our [Code of Conduct](code-of-conduct/), which applies across our community platform, digital and in person events." 
    right: 
      - icon: github
        href: https://github.com/
      - icon: linkedin 
        href: https://linkedin.com/company/communities-for-open-research-synthesis 
  reader-mode: true
  search: true


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

