---
title: "Join COReS Community"
---

# What is COReS?
Building a community around preclinical evidence synthesis
At COReS, we believe in transparency, reproducibility, and the power of the community.

Translational failure, where promising results from preclinical studies fail to show benefit in clinical practice, is a significant challenge in biomedical research. Systematic reviews of preclinical data, a robust method of evidence synthesis, offer a critical tool to uncover factors contributing to this translational gap. Armed with these insights, researchers can design studies of high translational value. Through transparent and reproducible research practices, COReS not only address this gap but also provides a platform for learning and networking.

With your active participation, and the value of reproducible and open data, we can improve the quality of preclinical (animal) research together to improve translational success. Let us explain.

Engaging with people and building communities has been vital to successful open science initiatives. That is why, we created COReS- Communities for Open Research Synthesis with a vision for it to become a strong open research community bringing together primary researchers and synthesists in the field of biomedical research.  At COReS, we want to raise awareness of the importance of preclinical systematic reviews for good science. By providing a comprehensive educational strategy focusing on evidence synthesis and preclinical animal research, we equip researchers with the right skillset and impetus to plan and conduct their own systematic review projects collaboratively. 

Our missionis to connect researchers in the preclinical space through an open community that encourages and supports them in the integration of preclinical systematic review into the research pipeline.  

The COReS community is supported by comprehensive educational resources on preclinical systematic review, as well as open access infrastructure and software.


# COReS – Join the community!

The COReS community members – you – can work collaboratively in research groups on different systematic review projects. Doing so, community members can add and verify information on our open space for preclinical research.

Our community is diverse, and the digital platform enables open discussion on current research.

## Benefits of joining the community

### Connect
Engage with fellow researchers on our digital community platform, fostering valuable connections. Enhance your network by participating in events and seize opportunities to grow your research horizons.

### Learn
Learn about evidence synthesis and how it can support you in evidece-based decision making for designing experiments. Gain insights into tools to support the desing of your experiments.

### Reproducible research
Improve the quality and reproducibility of your research. Transparent and open research methods, data, analysis and publication support research to be synthesizable.

## Digital Community Forum
Being part of the community means adhering to our Community Code of Conduct which applies across our community platform, digital and in person events. Have a suggestion to update the [Code of Conduct](), let us know by dropping us a line!

[Join the Discussion Forum](https://cores.zulipchat.com/)

### Who can you connect with on the digital platform? 

* Undergraduate and graduate students
* Researchers working with animals
* Synthesists, information specialists and statisticians
* Lab managers, veterinary specialists, 3Rs institutes
* Group leaders and Principle investigators
* Funders and policy makers

### We love welcoming new members
If you have a passion for evidence synthesis and preclinical animal research, we recommend joining the COReS community discussion forum hosted on Zulip. By becoming a community member, you will have the opportunity to collaborate with other researchers and synthesists who share your interests. Together, we can shape the future of translational research transparency.

Join us and let your voice be heard in the COReS community. We look forward to your valuable contributions!

