---
title: "Your Guide to COReS"
format: html
sidebar: Community
---

COReS (Communities for Open Research Synthesis) equips researchers to tackle the translational gap in biomedical research through systematic reviews of preclinical data.

- **Transparency & Reproducibility:** Open methods, open data, open code

- **Collaboration:** Shared learning, shared resources

- **Impact:** Better-designed experiments, fewer translational failures

To find out more about the COReS project, read our full mission & vision statement [here.](/about-cores/what-is-cores.qmd)




## Why Join?

::: panel-tabset
### 🔗 Connect {.tab}

-   Forge collaborations with students, PIs, and policy-makers\
-   Participate in events, discussion threads, and special interest groups\
-   Grow your network across disciplines

### 📚 Learn {.tab}

-   Access educational resources on systematic reviews & meta-analysis\
-   Try interactive tutorials and quizzes at your own pace\
-   Tap into expert office hours and webinars

### 🔄 Reproducible Research {.tab}

-   Be inspired to share protocols, data, and analysis scripts publicly\
-   Get acces to tools to improve study design\
-   Increase the rigor and impact of your preclinical research
:::



## Who can you interact with?

|  |  |
|------------------------------------|------------------------------------|
| 🎓 **Students** | 📊 **Synthesists** |
| Undergrads & grads learning evidence synthesis. | Statisticians & information specialists. |
| 🔬 **Researchers** | 💼 **Funders & Policy** |
| Animal-model experts & lab managers. | Shaping research priorities and best practices. |

## Creating an inclusive environment

::: {.callout-note icon=false}
## {{< fa hand-holding-hand >}} Code of Conduct
Our community thrives on respect and inclusivity. Please adhere to the code of conduct at all COReS events and workshops, including online spaces. Please review and help us improve it by adding your comments, its a living document by and for our community. 

[Review Code of Conduct →](/about-cores/code-of-conduct.qmd){.btn .btn-primary}
:::

## Get Started

:::: {.grid}
::: {.g-col-4}
::: {.callout-tip icon=false}
## {{< fa plus >}} New to COReS ?
Don't know where to get started with the COReS community? 
[Join the Community →](/about-cores/become-member.qmd){.btn .btn-secondary}
:::
:::

::: {.g-col-4}
::: {.callout-tip icon=false}
## {{< fa handshake >}} Want to Partner? 
What does being a COReS partner mean? Read our full guide. 
[Learn more →](/about-cores/become-partner.qmd){.btn .btn-secondary}
:::
:::

::: {.g-col-4}
::: {.callout-tip icon=false}
## {{< fa comments >}} Join the Conversation! 
Our community discussion forum is an active exchange of ideas! 
[Learn about the Forum →](about-cores/using-zulip.qmd){.btn .btn-secondary}
:::
:::
::::




:::: {.text-center style="margin-top: 1em"}
::: button

:::
::::
