---
title: "Become a Partner"
format: html
sidebar: Community
---


::: {.callout-tip icon=false}
## {{< fa file-circle-plus >}} Partner Guide
This is a summary of our partnership program. For detailed information, download our comprehensive [Partner Guide (PDF)](/files/Guide – COReS partners.pdf){target="_blank"}.
:::

## Our Vision
COReS partners are key players in establishing a strong open research community around preclinical systematic review. They champion the integration of systematic reviews into the research pipeline and help shape the future of evidence synthesis.

## Who Can Become a Partner?
- Individual researchers
- Research groups
- Research institutes
- Organizations experienced in systematic reviews

## Partnership Benefits

:::: {.grid}
::: {.g-col-6}
### 🤝 Community Leadership
- Shape evidence-based biomedical research
- Lead systematic review integration
- Influence research practices
:::

::: {.g-col-6}
### 📚 Resources & Support
- Access to educational programs
- Training materials
- Community discussion forum
- Regular field updates
:::
::::

## Partner Responsibilities
- Advocate for systematic reviews in your institution
- Participate in community development
- Support educational initiatives
- Follow our [Code of Conduct](/about-cores/code-of-conduct.qmd)
- Adhere to our [EDI Policy](/about-cores/policies.qmd)

## Our Current Partners
::: {.partner-grid}
| Institution | Contact |
|------------|----------|
| {{< fa arrow-up-right-from-square >}} [CAMARADES Berlin, BIH at Charité](https://www.bihealth.org/en/quest/service/service/camarades-facility-for-the-systematic-review-and-meta-analysis-1){target="_blank"} | Dr. Alexandra Bannach-Brown |
| {{< fa arrow-up-right-from-square >}} [RWTH Aachen](https://rwthcontacts.rwth-aachen.de/organization/ORG-39YHX){target="_blank"} | Dr. Julia Steitz |
| {{< fa arrow-up-right-from-square >}} [3R Freiburg](https://www.3rfreiburg.de/en){target="_blank"} | Dr. Ralf Watzlawick |
| {{< fa arrow-up-right-from-square >}} [Universität Münster](https://www.medizin.uni-muenster.de/neurologie/forschung/arbeitsgruppe-minnerup.html){target="_blank"} | Dr. Jens Minnerup |
| {{< fa arrow-up-right-from-square >}} [Universität Ulm](https://www.uni-ulm.de/einrichtungen/tfz/){target="_blank"} | Dr. Sibylle Ott |
| {{< fa arrow-up-right-from-square >}} [Universität Leipzig](https://www.vetmed.uni-leipzig.de/institut-fuer-tierhygiene-und-oeffentliches-veterinaerwesen){target="_blank"} | Dr. Beryl Eusemann |
:::

## Next Steps
1. [Review our partnership criteria in the detailed Partner Guide (PDF)](#)
2. [Contact us](mailto:camarades.berlin@charite.de) to schedule an initial discussion
3. Develop a collaborative agreement

::: {.callout-tip icon=false}
## {{< fa circle-plus >}} Ready to Join?
Email us at [camarades.berlin@charite.de](mailto:camarades.berlin@charite.de) to start the conversation.
:::



