---
title: "Policies"
format: html
sidebar: Community
---


## Equity, Diversity, and Inclusion

COReS recognises the significance of equity, diversity, and inclusion (EDI) among its members and in the wider research community. As a community initiative aiming to improve the quality of preclinical research to advance translational success, we value the input and contributions of our members from all backgrounds and levels of experience.

We engage with members and other relevant stakeholders with wide-ranging perspectives and needs, and actively foster an environment that is inclusive and welcoming for all. With the atmosphere we are creating, we would like members to feel valued, respected, and empowered to contribute to the community. We recognise that some of our community members face barriers and we are continuously working to lower and ultimately remove these.

At COReS, we value the use of inclusive language, we are thoughtful, respectful, and open in our communication, and we respect the diversity and backgrounds of our community members. Diversity goes beyond race, ethnicity, gender identity and expression, and also encompasses age, abilities, socio-economic status, sexual identity and orientation, and more.

COReS is committed to support EDI in all of our events, community interactions, and partnerships. Please have a look at our community guidelines (Code of Conduct), which applies to all COReS team and community members and includes measures against discrimination, harassment, bias, and exclusion.

We recognise that the research community is in a period of learning and are committed to continuous improvement in relation to EDI. We will regularly evaluate our practices to ensure they align with these values.

At COReS we are dedicated to fostering equity, diversity, and inclusion in our community and in all aspects of our work, and we encourage others to follow the same values and principles.

In case of inquiries, concerns, or feedback, please feel free to contact our Community Engagement Manager, Dr Friederike Elisabeth Kohrs at [friederike-elisabeth.kohrs\@charite.de](mailto:friederike-elisabeth.kohrs@charite.de).

## Logo & Colour Guidelines

It is important to the COReS community that we are represented consistenly across all platforms and forms of communication and dissemination. We have therefore created a style guide to serve as a blueprint. This guide outlines the guidelines and standards to be followed, encompassing aspects of branding, messaging, and visual representation.

Logo Guidelines: We provide clear instructions on how to use the COReS logo. From placement to sizing, our guidelines ensure that the COReS logo remains consistent and impactful. Download our logo in mulitple formats from our [Open Science Framework folder](https://osf.io/7zuex/){target="_blank"}.

Color and Typography Standards: Our style guide outlines the precise color palette and typography choices that align with our visual brand. Consistency in these elements reinforces our community’s visual identity.

View the comprehensive [COReS Style Guide here](https://osf.io/xt5b4/){target="_blank"}.

## Images & Infographics

The infographics displayed on the COReS website and materials were created by Meike Latz, PhD, a graphic designer based in Stockholm. For more information on her work, please visit: [meikelatz.com](https://meikelatz.com/){target="_blank"}.


## Privacy Policy

We will process personal data (from here on referred to as “data”) only to the extent required for the purpose of ensuring the functionality and user-friendliness of our website, its content, and the services we provide there.

According to the General Data Protection Regulation (from here on referred to as “GDPR”) Art. 4 No. 1 of Regulation (EU) 2016/679, “processing” refers to any operation or set of operations such as collection, recording, organization, structuring, storage, adaptation, alteration, retrieval, consultation, use, disclosure by transmission, dissemination, or otherwise making available, alignment, or combination, restriction, erasure, or destruction performed on personal data, whether by automated means or not.

The following privacy policy statement is designed to provide you, the website user, with detailed information, specifically regarding the type, scope, purpose, duration, and legal basis for the processing of this data, whether under our own control or in collaboration with others. Below, we also provide you with information about the third-party components we use to optimize our website and enhance the user experience, which might lead to these third parties independently processing data they collect and control.

Our privacy policy statement is structured as follows:

1.  Details about us as controllers for your data

2.  Rights granted to users and data subjects

3.  Information about data processing

4.  Information about the use of resources

### Details about us as controllers for your data

The data protection officer:

Data Protection officer at Charité – Universitätsmedizin Berlin
Campus Mitte
Charitéplatz 1
10117 Berlin, Germany

Telephone: +49 30 450 580 016
Email: [datenschutzbeauftragte\@charite.de](mailto:datenschutzbeauftragte@charite.de)

Website: [https://www.charite.de/en/service/data_protection/](https://www.charite.de/en/service/data_protection/){target="_blank"}


### Rights granted to users and data subjects

With regard to the data processing to be described in more detail below, users and data subjects have the right to

-   be informed whether and what data concerning them is being processed. Further, user and data subjects have the right to be informed about the type of the data processing and about copies of the data; Art. 15 GDPR

-   correct or complete incorrect or incomplete data; Art. 16 GDPR

-   demand the immediate deletion of data concerning them; Art 17 GDPR

-   restrict processing of data per Art. 18 GDPR, if further processing is stipulated in Art. 17 Para. 3 GDPR

-   request and receive copies of the data concerning them and/or provided by them and to have these data copies send to other providers/controllers; Art. 20 GDPR

-   file complaints with the supervisory authority if they believe that data concerning them is being processed by the controller in breach of data protection provisions; Art. 77 GDPR

In addition, the controller is obliged to inform all recipients to whom it discloses data of any such corrections, deletions, or restrictions placed on processing the same per Art. 16, 17 Para. 1, 18 GDPR. However, this obligation does not apply if such notification is impossible or involves a disproportionate effort. Nevertheless, users have a right to information about these recipients.

Likewise, under Art. 21 GDPR, users and data subjects have the right to object to the controller's future processing of their data pursuant to Art. 6 Para. 1 lit. f) GDPR. In particular, an objection to data processing for the purpose of direct advertising is permissible.


### Information about data processing

When using our website, your processed data will be deleted or blocked once the purpose for its storage ceases to apply, provided the deletion of the same data is not in breach of a statutory storage obligations or unless otherwise stipulated below.


#### Server data

For technical reasons, the data transmitted by your web browser to us or our service provider will be gathered. This is especially to guarantee the security and stability of our website. These server log files will include information such as your browser type and version, operating system, the referring URL (the website from which you arrived), the specific pages you accessed in our site, the dat and time of your visit, and the IP address from which you accessed our site.

The data collected in this manner will be temporarily stored, without being linked to any other of your data.

The basis for this storage is Art. 6 Para. 1 lit. f) GDPR. Our legitimate interest lies in the improvement, stability, functionality, and security of our website.

The collected data will be erased within a maximum of seven days, unless its continued storage is necessary for the purpose of preserving evidence. If so, some or all of the data will be exempted from deletion until the investigation of the relevant incident reaches a final conclusion.


#### Cookies

**a) Session cookies**

We use cookies on our website. Cookies are compact text files or alternative storage technologies that your browser saves on your computer. These cookies process specific information about you, such as your browser, location data, or IP address.

This processing makes our website more user-friendly, efficient, and secure.

The legal basis for such processing is Art. 6 Para. 1 lit. b) GDPR, insofar as these cookies are used to collect data to initiate or process contractual relationships.

If the processing does not serve to initiate or process a contract, our legitimate interest lies in improving the functionality of our website. The legal basis is then Art. 6 Para. 1 lit. f) GDPR.

Upon closing your browser, these session cookies are erased.

**b) Disabling cookies**

You have the option to decline the utilization of cookies by adjusting your browser settings. Moreover, you can utilize your browser to eliminate cookies already stored. Please be aware that the procedures and actions needed for this may vary based on the specific browser you are using. For any queries, we suggest referring to your browser’s documentation or reaching out to the manufacturer for assistance.

It’s important to note that modifying browser settings cannot prevent so-called flash cookies from being set. In this case, you will need to modify your Flash player’s settings. The specific steps and actions required for this will also depend on the version of Flash player you have. If you have any inquiries, please make use of the Flash player’s help feature, refer to the documentation provided with your player, or contact its manufacturer for support.

Should you choose to block or limit the installation of cookies, some of the features on our site may not be fully accessible or functional.

**Contact**

When you get in touch with us through email or the contact form, the data you provide will be used exclusively to process your request. This data is essential for processing and responding to your request. Without this information, we may not be able to provide a comprehensive or any response to your inquiry.

The legal basis for this data processing is Art. 6 Para. 1 lit. b) GDPR.

Your data will be deleted once we have fully answered your inquiry and there is no further legal obligation to store your data.

**WordPress**

When you submit an enquiry through our contact form(s) we collect your name, email address and any text information submitted in the message. We keep this information for up to three years for grant reporting purposes. We do not use this information for marketing purposes.

**Zulip (Kandra Labs, Inc.)**

Zulip provides communication platform services. By accessing or using Zulip serivces you agree to the collection, usage, and sharing of personal information. Data collection and processing adheres to the GDPR. Data will be collected which is needed to provide the best service to you. Personal information will not be sold to third parties. Zulip employs cookies and similar technologies to enable their servers to recognize information on the user’s device, allowing for an analysis of the user behavior on the communication platform.

More information is available at: [https://zulip.com/policies/privacy](https://zulip.com/policies/privacy){target="_blank"}

**MailChimp - Newsletter**

MailChimp (and it’s parent company Intuit) attaches particular importance to the respect for the privacy of the users and of the confidentiality of their personal data, and is thus committed to processing the data in compliance with the applicable data protection laws and regulations. Intuit and Mailchimp comply with the EU-U.S. Data Privacy Framework (EU-U.S. DPF), the UK Extension to the EU-U.S. DPF, and the Swiss-U.S. Data Privacy Framework (Swiss-U.S. DPF) regarding the collection, use, and retention of personal information transferred from the European Union (EU), the United Kingdom (and Gibraltar), and Switzerland to the United States. Intuit and Mailchimp rely on the EU-U.S. DPF to transfer data and will rely on the UK Extension to the EU-U.S. DPF and Swiss-U.S. DPF once approved by the appropriate authorities. They are subject to the investigatory and enforcement powers of the Federal Trade Commission.

More information is available at [https://www.intuit.com/privacy/statement/](https://www.intuit.com/privacy/statement/){target="_blank"}

### Information about the use of resources

**Copyright compliance and disclaimer**

We adhere to copyright laws and ensure that all content in our website is utilized in a manner that upholds the intellectual property rights of creators and respects the privacy rights of individuals featured in the materials. Specifically:

we collect consent from the people visible in our materials,

and we comply with the Fair Use principles and the Creative Commons copyright licences when using third-party materials.

Consequently, it is not permissible to reproduce, alter, redistribute, commercially exploit, or reuse any of the materials from our website without the prior written consent to both the creator and individuals featured in them. As a result, we cannot assume responsibility for any content from our website that us reproduced, redistributed, or reused by a third party.

**Third-party resources**

The third-party resources linked on the COReS website aim to offer public access to the COReS project’s activities and outcomes. Although we exercise care in incorporating third-party materials on our website, we cannot guarantee their accuracy, completeness, or currentness, nor do we accept any responsibility for the content.
